apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: week1-frontend-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: mindx-minhnh.135.171.192.18.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: week1-frontend-service
            port:
              number: 80
  tls:
  - hosts:
    - mindx-minhnh.135.171.192.18.nip.io
    secretName: mindx-tls-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: week1-api-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: mindx-minhnh.135.171.192.18.nip.io
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: week1-api-service
            port:
              number: 3000
  tls:
  - hosts:
    - mindx-minhnh.135.171.192.18.nip.io
    secretName: mindx-tls-cert
