apiVersion: v1
kind: Service
metadata:
  name: week1-api-service
  labels:
    app: week1-api
spec:
  selector:
    app: week1-api
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP