apiVersion: v1
kind: Service
metadata:
  name: week1-frontend-service
  labels:
    app: week1-frontend
spec:
  selector:
    app: week1-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP